package org.daubin.js.database;

/**
 * This interface is used like a mixin on the model classes generated by {@link DatabaseContext#define(String, java.util.Map)}.
 * @author sdaubin
 */
public interface Model {

	default String help() {
		return "";
	}
}
